/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/joonas/repos/Hiab/HLSIMU/screen-mirror/src/hlsim-dds-interfaces/src/generated/Time.h
  Source: /home/joonas/repos/Hiab/HLSIMU/screen-mirror/src/hlsim-dds-interfaces/src/Time.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_JOONAS_REPOS_HIAB_HLSIMU_SCREEN_MIRROR_SRC_HLSIM_DDS_INTERFACES_SRC_GENERATED_TIME_H
#define DDSC__HOME_JOONAS_REPOS_HIAB_HLSIMU_SCREEN_MIRROR_SRC_HLSIM_DDS_INTERFACES_SRC_GENERATED_TIME_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_dds__Time_
{
  int32_t sec;
  uint32_t nanosec;
} std_msgs_msg_dds__Time_;

extern const dds_topic_descriptor_t std_msgs_msg_dds__Time__desc;

#define std_msgs_msg_dds__Time___alloc() \
((std_msgs_msg_dds__Time_*) dds_alloc (sizeof (std_msgs_msg_dds__Time_)));

#define std_msgs_msg_dds__Time__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_dds__Time__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_JOONAS_REPOS_HIAB_HLSIMU_SCREEN_MIRROR_SRC_HLSIM_DDS_INTERFACES_SRC_GENERATED_TIME_H */
